#!/bin/bash

ARG=$1

# monitors
INTERNAL=$(xrandr | grep "eDP1 connected" &> /dev/null && echo 1 || echo 0)
DOCKONE=$(xrandr | grep "HDMI2 connected" &> /dev/null && echo 1 || echo 0)
DOCKTWO=$(xrandr | grep "HDMI3 connected" &> /dev/null && echo 1 || echo 0)
VGA=$(xrandr | grep "VGA1 connected" &> /dev/null && echo 1 || echo 0)

function xinitCall(){
if [ $INTERNAL -eq 1 ]; then
   if [ $DOCKONE -eq 1 ] && [ $DOCKTWO -eq 1 ]; then
      # xrandr --output HDMI3 --auto --primary --output HDMI2 --auto --right-of HDMI3 --output eDP1 --off
      xrandr --output eDP1 --off
      xrandr --output HDMI3 --auto --primary --output HDMI2 --auto --right-of HDMI3
   else
      xrandr --output HDMI3 --off --output HDMI2 --off
      xrandr --output eDP1 --auto
   fi
fi
}

function vgaCall(){
xrandr --output eDP1 --auto --primary --output VGA1 --auto --right-of eDP1
}

if [ -n "$ARG" ]; then
   if [ "$ARG" == "--startup" ]; then
      xinitCall
   fi
elif [ $VGA -eq 1 ]; then
   vgaCall
fi
