#!/bin/bash

AMASTER=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $6}'`

if [[ "$AMASTER" == "off" ]]; then
    amixer set Master on
    amixer set Headphone on
    amixer set Speaker+LO on
else
    amixer set Master off
    amixer set Headphone off
    amixer set Speaker+LO off
fi
