#!/bin/bash

# start standard programs
declare -A progs
progs[firefox]='firefox'
#progs[mutt]='urxvtc -e mutt'
progs[always2]='ssh-add'
progs[always3]='urxvtc'

for i in "${!progs[@]}"; do
    if [ $(pgrep -cx $i) -lt 1 ] ; then
        eval ${progs[$i]} &
    fi
done

# mount wmii filesystem
#9mount -i 'unix!'/tmp/ns.$USER.$DISPLAY/wmii .mntwmii &
