#!/bin/bash
clr=$WMII_NORMCOLORS
lbl=">^_^<"

if [[ $(hostname) == "satomi" ]]; then
    BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
    STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`

    if [[ $STATUS = "Discharging" ]]; then
        lbl="$BAT% --"
        if [[ $BAT -lt 20 ]]; then
            sleep 0.5
            echo colors $clr | wmiir write /rbar/battery
            clr="#1c1c1c #ff005b #666666"
        elif [[ $BAT -lt 40 ]]; then
            clr="#1c1c1c #ff9f00 #666666"
        fi
    elif [[ $STATUS = "Charging" ]]; then
        lbl="$BAT% ++"
        if [[ $BAT -lt 20 ]]; then
            clr="#1c1c1c #ff0000 #666666"
        elif [[ $BAT -lt 40 ]]; then
            clr="#1c1c1c #ff9f00 #666666"
        fi
    elif [[ $STATUS = "Full" ]]; then
        lbl="=^.^="
    fi
    sleep 0.5
fi

echo colors $clr | wmiir write /rbar/battery
echo -n label $lbl | wmiir write /rbar/battery
