#!/bin/bash
BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`


if [[ $STATUS = "Discharging" ]]; then
    echo "$BAT% --"
elif [[ $STATUS = "Charging" ]]; then
    echo "$BAT% ++"
elif [[ $STATUS = "Full" ]]; then
    echo "=^.^="
else
    echo ">*_*<"
fi
