#!/bin/bash

DEVICE=$(ip link |grep 'wlp*' | awk '{gsub(/[:/"/]/," "); print $2}')
QUAL=$(/sbin/iwconfig $DEVICE | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}')
MAX=$(/sbin/iwconfig $DEVICE | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}')
PERC=$(echo $QUAL*100/$MAX |bc)

NAME=$(/sbin/iwconfig $DEVICE | grep 'ESSID' |  awk '{gsub(/[:/"/]/," "); print $5}')

echo "$NAME: $PERC%"
