#!/bin/bash
source $(dirname $0)/config

QUAL=$(iwconfig wlp4s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}')
MAX=$(iwconfig wlp4s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}')
PERC=$(echo $QUAL*100/$MAX |bc)

name=$(iwconfig wlp4s0 | grep 'ESSID' |  awk '{gsub(/[:/"/]/," "); print $5}')

icon=""

echo "$name: $PERC"
